@startuml
skinparam ClassAttributeIconSize 0
skinparam Monochrome true
hide circle
class Namn {
    + Förnamn : string <<get>> <<set>>
    + Efternamn : string <<get>> <<set>>
    + VisaNamn() : void
}
class Program {
    {static} Main(args:string[]) : void
}
@enduml
